<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFo6poTb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFo6poTb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFo6poTb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFo6poTb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFo6poTb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Fo6poTb',
    'container.build_id' => 'dc25ceb9',
    'container.build_time' => 1707695833,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFo6poTb');
