<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvebQMh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvebQMh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNvebQMh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNvebQMh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNvebQMh\App_KernelDevDebugContainer([
    'container.build_hash' => 'NvebQMh',
    'container.build_id' => '4c108615',
    'container.build_time' => 1708462226,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvebQMh');
