<?php

namespace ContainerXc120Va;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DTaHD7mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dTaHD7m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dTaHD7m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', true],
            'passwordHasher' => ['privates', '.errored..service_locator.dTaHD7m.Symfony\\Component\\PasswordHasher\\Hasher\\UserPasswordHasherInterface', NULL, 'Cannot autowire service ".service_locator.dTaHD7m": it references interface "Symfony\\Component\\PasswordHasher\\Hasher\\UserPasswordHasherInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'doctrine' => '?',
            'passwordHasher' => 'Symfony\\Component\\PasswordHasher\\Hasher\\UserPasswordHasherInterface',
        ]);
    }
}
