<?php

namespace ContainerXc120Va;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPasswordHasherInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.dTaHD7m.Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface' shared service.
     *
     * @return \Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.dTaHD7m": it references interface "Symfony\\Component\\PasswordHasher\\Hasher\\UserPasswordHasherInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
